### ISSUE TITLE
Point Twitter feed on home page at @swiftfest

### ISSUE THREAD

**Issue by ZevEisenberg** [ZevEisenberg/swiftfest-site#13]
Or delete this section if we aren't planning on using it.

**Comment by ZevEisenberg** [comment]
From _config.yml:

```yml
# Tweets Feed Block
# TODO: need to set up tweetledee or delete this section https://github.com/tweetledee/tweetledee
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "swiftfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"
```
